/* Generated By:JavaCC: Do not edit this line. SqlNormalizerConstants.java */
package datadog.trace.instrumentation.jdbc.normalizer;

/** Token literal values and constants. Generated by org.javacc.parser.OtherFilesGen#start() */
public interface SqlNormalizerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int Id = 1;
  /** RegularExpression Id. */
  int BasicNum = 2;
  /** RegularExpression Id. */
  int HexNum = 3;
  /** RegularExpression Id. */
  int QuotedStr = 4;
  /** RegularExpression Id. */
  int DoubleQuotedStr = 5;
  /** RegularExpression Id. */
  int Whitespace = 6;
  /** RegularExpression Id. */
  int Other = 7;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<Id>",
    "<BasicNum>",
    "<HexNum>",
    "<QuotedStr>",
    "<DoubleQuotedStr>",
    "<Whitespace>",
    "<Other>",
  };
}
